#:schema node_modules/wrangler/config-schema.json
name = "cazcik"
main = ".worker-next/index.mjs"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

minify = true

assets = { directory = ".worker-next/assets", binding = "ASSETS" }

routes = [
    { pattern = "cazcik.com", custom_domain = true }
]

[observability]
enabled = true