name: build and deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: setup bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: make scripts executable
      run: |
        chmod +x scripts/build.sh
        chmod +x scripts/deploy.sh
        
    - name: build site
      run: ./scripts/build.sh
      
    - name: setup ssh key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
     
    - name: login to tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
        
    - name: add host to known hosts
      run: |
        echo "Attempting to connect to: ${{ secrets.DEPLOY_TARGET }}"
        echo "Testing connectivity..."
        ping -c 3 ${{ secrets.DEPLOY_TARGET }} || echo "Ping failed, but continuing..."
        echo "Testing SSH port..."
        nc -zv ${{ secrets.DEPLOY_TARGET }} 22 || echo "SSH port test failed, but continuing..."
        echo "Running ssh-keyscan..."
        ssh-keyscan -H ${{ secrets.DEPLOY_TARGET }} >> ~/.ssh/known_hosts || echo "ssh-keyscan failed, but continuing..."
        
    - name: deploy to server
      run: |
        echo "Deploying to target: ${{ secrets.DEPLOY_TARGET }}"
        echo "Deploying as user: ${{ secrets.DEPLOY_USER }}"
        echo "Deploying to destination: ${{ secrets.DEPLOY_DESTINATION }}"
        echo "Using key file: ~/.ssh/deploy_key"
        echo "Deploying assets from: ./dist"
        
        # Test SSH connection manually first
        echo "Testing SSH connection..."
        ssh -i ~/.ssh/deploy_key -o ConnectTimeout=10 -o BatchMode=yes ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_TARGET }} "echo 'SSH connection test successful'" || echo "SSH connection test failed"
        
        ./scripts/deploy.sh \
          --target ${{ secrets.DEPLOY_TARGET }} \
          --destination ${{ secrets.DEPLOY_DESTINATION }} \
          --user ${{ secrets.DEPLOY_USER }} \
          --key ~/.ssh/deploy_key \
          --assets ./dist